const ApiResults = [
	{
		uri: "spotify:track:53kmT0IrNAVyyyMw69WhSf",
		name: "Time Time",
		artist: "GOLDEN G",
		album: "What If It's Me",
		albumArt: "./components_styles/images/what_if_its_me.jpg",
	},
	{
		uri: "spotify:track:31KqBmqaU1CHdzkN0E5KwN",
		name: "R-Bomb",
		artist: "GOLDEN G",
		album: "What If It's Me",
		albumArt: "./components_styles/images/what_if_its_me.jpg",
	},
	{
		uri: "spotify:track:4EZ6ZIzTEYSzgtwoybXxWo",
		name: "Wrong Ones",
		artist: "GOLDEN G",
		album: "What If It's Me",
		albumArt: "./components_styles/images/what_if_its_me.jpg",
	},
	{
		uri: "spotify:track:2XJRwRnrfoCsGh85efL5sM",
		name: "Snakes and Ladders",
		artist: "GOLDEN G",
		album: "What If It's Me",
		albumArt: "./components_styles/images/what_if_its_me.jpg",
	},
	{
		uri: "spotify:track:1liesF9zaiXa2oIlVmy0Ne",
		name: "Dream Works",
		artist: "GOLDEN G",
		album: "What If It's Me",
		albumArt: "./components_styles/images/what_if_its_me.jpg",
	},
	{
		uri: "spotify:track:5rYVsKCvhTrKvV8cWMLRBK",
		name: "Kahuna",
		artist: "GOLDEN G",
		album: "What If It's Me",
		albumArt: "./components_styles/images/what_if_its_me.jpg",
	},
	{
		uri: "spotify:track:5wwxMK41CZhp7CxNLwtOsz",
		name: "Say It Ain't So",
		artist: "GOLDEN G",
		album: "What If It's Me",
		albumArt: "./components_styles/images/what_if_its_me.jpg",
	},
	{
		uri: "spotify:track:1lPuy6pHLOkAqMkfxZtHbB",
		name: "Wiim Freestyle",
		artist: "GOLDEN G",
		album: "What If It's Me",
		albumArt: "./components_styles/images/what_if_its_me.jpg",
	},
	{
		uri: "spotify:track:4dYmC1mK5MflyOPS3846sc",
		name: "Skydive",
		artist: "GOLDEN G",
		album: "What If It's Me",
		albumArt: "./components_styles/images/what_if_its_me.jpg",
	},
	{
		uri: "spotify:track:2hHSwKRq3MY5w3GhIXWabG",
		name: "Selfish",
		artist: "GOLDEN G",
		album: "What If It's Me",
		albumArt: "./components_styles/images/what_if_its_me.jpg",
	},
	{
		uri: "spotify:track:3SIZibyUc2cwH4q2H6ubqB",
		name: "Trust",
		artist: "GOLDEN G",
		album: "What If It's Me",
		albumArt: "./components_styles/images/what_if_its_me.jpg",
	},
	{
		uri: "spotify:track:1ykdcqqMgmn1tBkHdEKe3e",
		name: "Full Flight",
		artist: "GOLDEN G",
		album: "What If It's Me",
		albumArt: "./components_styles/images/what_if_its_me.jpg",
	},
	{
		uri: "spotify:track:3AOQKVGsQibEnhZli4Hdz7",
		name: "48",
		artist: "GOLDEN G",
		album: "What If It's Me",
		albumArt: "./components_styles/images/what_if_its_me.jpg",
	},
	{
		uri: "spotify:track:4CHpXBkWWCdgno2Dl5ZxVb",
		name: "2 or 3",
		artist: "GOLDEN G",
		album: "What If It's Me",
		albumArt: "./components_styles/images/what_if_its_me.jpg",
	},
	{
		uri: "spotify:track:25qX1NqEJHCVm5N8Yyuli6",
		name: "Kelsey's Freestyle",
		artist: "GOLDEN G",
		album: "What If It's Me",
		albumArt: "./components_styles/images/what_if_its_me.jpg",
	},
	{
		uri: "spotify:track:11bbGE698YzjwEoX0MseII",
		name: "Make You Feel Awright",
		artist: "GOLDEN G",
		album: "What If It's Me",
		albumArt: "./components_styles/images/what_if_its_me.jpg",
	},
	{
		uri: "spotify:track:590meBMp5gcoGkoIA26Wkt",
		name: "What If It's Me",
		artist: "GOLDEN G",
		album: "What If It's Me",
		albumArt: "./components_styles/images/what_if_its_me.jpg",
	},
];

export default ApiResults;
